import { GENERAL_EXPENSE_CATEGORIES, RECURRING_EXPENSE_CATEGORIES } from './categories';

function makeExpenseRecord({
  id,
  date,
  amount,
  category,
  paymentMethod = '카드',
  type = '일반',
  memo = '',
  sourceRecurringId,
  monthKey,
}) {
  const record = {
    id,
    date,
    amount: String(amount),
    category,
    paymentMethod,
    type,
    memo,
  };

  if (sourceRecurringId) {
    record.sourceRecurringId = sourceRecurringId;
  }

  if (monthKey) {
    record.monthKey = monthKey;
  }

  return record;
}

function makeRecurringExpense({
  id,
  name,
  amount,
  paymentDay,
  category,
  paymentMethod = '카드',
  memo = '',
}) {
  return {
    id,
    name,
    amount: String(amount),
    paymentDay: String(paymentDay),
    category,
    paymentMethod,
    memo,
  };
}

function makeMonthlyBudgetSnapshot({
  monthlyIncome,
  budgetSettings,
  savingGoalSettings,
  createdAt = '2026-06-01T00:00:00.000Z',
}) {
  return {
    monthlyIncome,
    budgetSettings: { ...budgetSettings },
    savingGoalSettings: { ...savingGoalSettings },
    fixedExpenses: String(budgetSettings?.fixedExpenseAmount || '0'),
    savingGoal: String(savingGoalSettings?.goalAmount || '0'),
    emergencyFund: String(budgetSettings?.emergencyFundAmount || '0'),
    createdAt,
    updatedAt: createdAt,
  };
}

const firstAccount = {
  name: '테스트사용자',
  email: '1234@naver.com',
  password: '1234',
  monthlyIncome: 2500000,
  budgetSettings: {
    useManualBudget: false,
    manualDailyBudget: '30000',
    manualDailyBudgetEnabled: true,
    fixedExpenseAmount: '0',
    autoIncludeRecurringExpenses: true,
    emergencyFundAmount: '100000',
    goalEnabled: true,
    periodCalculationEnabled: true,
    carryOverEnabled: true,
    carryOverAmount: '0',
    manualCarryOverEnabled: false,
    manualCarryOverAmount: '0',
  },
  savingGoalSettings: {
    goalAmount: '300000',
    goalPeriod: '30',
    currentSaving: '0',
  },
  carryOverState: {
    lastCalculatedMonth: '2026-05',
    monthlySnapshots: {
      '2026-04': {
        remainingAmount: 200000,
        automaticCarryOverAmount: 200000,
        calculatedAt: '2026-05-01T00:00:00.000Z',
      },
      '2026-05': {
        automaticCarryOverAmount: 200000,
        calculatedAt: '2026-05-01T00:00:00.000Z',
      },
    },
  },
  savingGoals: [
    {
      id: 'seed-goal-01',
      name: '노트북 구매',
      category: '전자기기',
      targetAmount: '1000000',
      currentAmount: '1000000',
      deadline: '2026-08-31',
    },
    {
      id: 'seed-goal-02',
      name: '유럽 여행',
      category: '여행',
      targetAmount: '1500000',
      currentAmount: '600000',
      deadline: '2026-10-15',
    },
    {
      id: 'seed-goal-03',
      name: '비상금',
      category: '비상금',
      targetAmount: '2000000',
      currentAmount: '800000',
      deadline: '2026-12-31',
    },
  ],
  budgetsByMonth: {
    '2026-05': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2500000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '30000',
        manualDailyBudgetEnabled: true,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '100000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: true,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '300000',
        goalPeriod: '30',
        currentSaving: '0',
      },
      createdAt: '2026-05-01T00:00:00.000Z',
    }),
    '2026-06': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2500000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '30000',
        manualDailyBudgetEnabled: true,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '100000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: true,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '300000',
        goalPeriod: '30',
        currentSaving: '0',
      },
    }),
  },
  recurringExpenses: [
    makeRecurringExpense({
      id: 'seed-recurring-01',
      name: '기숙사비',
      amount: 180000,
      paymentDay: 1,
      category: RECURRING_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
      memo: '공과금 포함 기숙사비',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-02',
      name: '휴대폰 요금',
      amount: 59000,
      paymentDay: 10,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-03',
      name: '인터넷 요금',
      amount: 33000,
      paymentDay: 8,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-04',
      name: '넷플릭스',
      amount: 12000,
      paymentDay: 15,
      category: RECURRING_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-05',
      name: '유튜브 프리미엄',
      amount: 10450,
      paymentDay: 5,
      category: RECURRING_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-06',
      name: '보험료',
      amount: 45000,
      paymentDay: 7,
      category: RECURRING_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-07',
      name: '교통 정기권',
      amount: 62000,
      paymentDay: 31,
      category: RECURRING_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'seed-recurring-08',
      name: '청약저축',
      amount: 20000,
      paymentDay: 10,
      category: RECURRING_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
  ],
  expenseRecords: [
    makeExpenseRecord({
      id: 'seed-expense-01',
      date: '2026-03-03T09:00:00',
      amount: 30000,
      category: GENERAL_EXPENSE_CATEGORIES[6],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-02',
      date: '2026-03-05T12:00:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-03',
      date: '2026-03-08T08:30:00',
      amount: 22000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-04',
      date: '2026-03-10T10:40:00',
      amount: 8000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-05',
      date: '2026-03-15T18:20:00',
      amount: 14000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-06',
      date: '2026-03-21T20:00:00',
      amount: 10000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-07',
      date: '2026-03-27T14:00:00',
      amount: 22000,
      category: GENERAL_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-08',
      date: '2026-04-01T08:00:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-09',
      date: '2026-04-05T11:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-10',
      date: '2026-04-08T12:40:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-11',
      date: '2026-04-12T17:15:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-12',
      date: '2026-04-18T19:30:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-13',
      date: '2026-04-28T21:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[6],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-14',
      date: '2026-05-02T08:00:00',
      amount: 140000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-15',
      date: '2026-05-03T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-16',
      date: '2026-05-09T09:00:00',
      amount: 10450,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-17',
      date: '2026-06-02T08:30:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-18',
      date: '2026-06-08T12:10:00',
      amount: 8000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-19',
      date: '2026-06-14T19:20:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-20',
      date: '2026-06-20T21:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-21',
      date: '2026-06-24T09:30:00',
      amount: 28000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'seed-expense-22',
      date: '2026-06-15T13:00:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
  ],
};

const secondAccount = {
  name: '대학생테스트',
  email: 'student@pingo.com',
  password: '12345',
  monthlyIncome: 2400000,
  budgetSettings: {
    useManualBudget: false,
    manualDailyBudget: '',
    manualDailyBudgetEnabled: false,
    fixedExpenseAmount: '0',
    autoIncludeRecurringExpenses: true,
    emergencyFundAmount: '50000',
    goalEnabled: true,
    periodCalculationEnabled: true,
    carryOverEnabled: false,
    carryOverAmount: '0',
    manualCarryOverEnabled: false,
    manualCarryOverAmount: '0',
  },
  savingGoalSettings: {
    goalAmount: '500000',
    goalPeriod: '90',
    currentSaving: '100000',
  },
  savingGoals: [
    {
      id: 'student-goal-01',
      name: '자격증 응시료',
      category: '자격증',
      targetAmount: '200000',
      currentAmount: '50000',
      deadline: '2026-06-30',
    },
    {
      id: 'student-goal-02',
      name: '졸업사진 촬영비',
      category: '기타',
      targetAmount: '300000',
      currentAmount: '100000',
      deadline: '2026-04-15',
    },
  ],
  budgetsByMonth: {
    '2026-05': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2400000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '500000',
        goalPeriod: '90',
        currentSaving: '100000',
      },
      createdAt: '2026-05-01T00:00:00.000Z',
    }),
    '2026-06': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2400000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '500000',
        goalPeriod: '90',
        currentSaving: '100000',
      },
    }),
  },
  recurringExpenses: [
    makeRecurringExpense({
      id: 'student-recurring-01',
      name: '기숙사비',
      amount: 120000,
      paymentDay: 1,
      category: RECURRING_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'student-recurring-02',
      name: '휴대폰 요금',
      amount: 45000,
      paymentDay: 9,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'student-recurring-03',
      name: '인터넷 요금',
      amount: 33000,
      paymentDay: 8,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'student-recurring-04',
      name: '넷플릭스',
      amount: 12000,
      paymentDay: 15,
      category: RECURRING_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'student-recurring-05',
      name: '보험료',
      amount: 40000,
      paymentDay: 7,
      category: RECURRING_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'student-recurring-06',
      name: '교통 정기권',
      amount: 55000,
      paymentDay: 31,
      category: RECURRING_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
  ],
  expenseRecords: [
    makeExpenseRecord({
      id: 'student-expense-01',
      date: '2026-03-03T10:00:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-02',
      date: '2026-03-07T11:00:00',
      amount: 10000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-03',
      date: '2026-03-12T13:20:00',
      amount: 8000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-04',
      date: '2026-03-18T18:40:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-05',
      date: '2026-03-25T20:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-06',
      date: '2026-04-01T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-07',
      date: '2026-04-06T09:30:00',
      amount: 30000,
      category: GENERAL_EXPENSE_CATEGORIES[6],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-08',
      date: '2026-04-11T10:20:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-09',
      date: '2026-04-17T12:10:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-10',
      date: '2026-04-23T21:00:00',
      amount: 17000,
      category: GENERAL_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-11',
      date: '2026-05-03T08:30:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-12',
      date: '2026-05-09T09:00:00',
      amount: 24000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-13',
      date: '2026-05-10T09:00:00',
      amount: 65000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-14',
      date: '2026-05-11T09:00:00',
      amount: 50000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-15',
      date: '2026-06-01T09:00:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-16',
      date: '2026-06-04T11:30:00',
      amount: 10000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-17',
      date: '2026-06-09T13:10:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-18',
      date: '2026-06-17T18:40:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-19',
      date: '2026-06-24T09:00:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'student-expense-20',
      date: '2026-06-15T12:30:00',
      amount: 50000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
  ],
};

const dangerAccount = {
  name: '위험테스트',
  email: 'danger@pingo.com',
  password: '12345',
  monthlyIncome: 2200000,
  budgetSettings: {
    useManualBudget: false,
    manualDailyBudget: '',
    manualDailyBudgetEnabled: false,
    fixedExpenseAmount: '0',
    autoIncludeRecurringExpenses: true,
    emergencyFundAmount: '50000',
    goalEnabled: true,
    periodCalculationEnabled: true,
    carryOverEnabled: false,
    carryOverAmount: '0',
    manualCarryOverEnabled: false,
    manualCarryOverAmount: '0',
  },
  savingGoalSettings: {
    goalAmount: '500000',
    goalPeriod: '90',
    currentSaving: '100000',
  },
  savingGoals: [
    {
      id: 'danger-goal-01',
      name: '자격증 응시료',
      category: '자기계발',
      targetAmount: '200000',
      currentAmount: '50000',
      deadline: '2026-06-30',
    },
    {
      id: 'danger-goal-02',
      name: '졸업사진 촬영비',
      category: '기타',
      targetAmount: '300000',
      currentAmount: '100000',
      deadline: '2026-04-15',
    },
  ],
  budgetsByMonth: {
    '2026-05': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2200000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '500000',
        goalPeriod: '90',
        currentSaving: '100000',
      },
      createdAt: '2026-05-01T00:00:00.000Z',
    }),
    '2026-06': makeMonthlyBudgetSnapshot({
      monthlyIncome: 2200000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '0',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '500000',
        goalPeriod: '90',
        currentSaving: '100000',
      },
    }),
  },
  recurringExpenses: [
    makeRecurringExpense({
      id: 'danger-recurring-01',
      name: '기숙사비',
      amount: 120000,
      paymentDay: 1,
      category: RECURRING_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'danger-recurring-02',
      name: '휴대폰 요금',
      amount: 45000,
      paymentDay: 9,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'danger-recurring-03',
      name: '인터넷 요금',
      amount: 33000,
      paymentDay: 8,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'danger-recurring-04',
      name: '넷플릭스',
      amount: 12000,
      paymentDay: 15,
      category: RECURRING_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'danger-recurring-05',
      name: '보험료',
      amount: 40000,
      paymentDay: 7,
      category: RECURRING_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'danger-recurring-06',
      name: '교통 정기권',
      amount: 55000,
      paymentDay: 31,
      category: RECURRING_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
  ],
  expenseRecords: [
    makeExpenseRecord({
      id: 'danger-expense-01',
      date: '2026-03-03T10:00:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-02',
      date: '2026-03-07T11:00:00',
      amount: 10000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-03',
      date: '2026-03-12T13:20:00',
      amount: 8000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-04',
      date: '2026-03-18T18:40:00',
      amount: 12000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-05',
      date: '2026-03-25T20:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-06',
      date: '2026-04-01T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-07',
      date: '2026-04-06T09:30:00',
      amount: 30000,
      category: GENERAL_EXPENSE_CATEGORIES[6],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-08',
      date: '2026-04-11T10:20:00',
      amount: 15000,
      category: GENERAL_EXPENSE_CATEGORIES[3],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-09',
      date: '2026-04-17T12:10:00',
      amount: 18000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-10',
      date: '2026-04-23T21:00:00',
      amount: 17000,
      category: GENERAL_EXPENSE_CATEGORIES[4],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-11',
      date: '2026-05-03T08:30:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-12',
      date: '2026-05-09T09:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-13',
      date: '2026-05-10T09:00:00',
      amount: 75000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-14',
      date: '2026-05-11T09:00:00',
      amount: 55000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-15',
      date: '2026-06-01T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-16',
      date: '2026-06-03T11:00:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-17',
      date: '2026-06-07T14:20:00',
      amount: 35000,
      category: GENERAL_EXPENSE_CATEGORIES[6],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-18',
      date: '2026-06-16T19:00:00',
      amount: 40000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-19',
      date: '2026-06-24T21:10:00',
      amount: 50000,
      category: GENERAL_EXPENSE_CATEGORIES[8],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'danger-expense-20',
      date: '2026-06-15T12:30:00',
      amount: 58000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
  ],
};

const overbudgetAccount = {
  name: '초과테스트',
  email: 'overbudget@pingo.com',
  password: '12345',
  monthlyIncome: 450000,
  budgetSettings: {
    useManualBudget: false,
    manualDailyBudget: '',
    manualDailyBudgetEnabled: false,
    fixedExpenseAmount: '100000',
    autoIncludeRecurringExpenses: true,
    emergencyFundAmount: '50000',
    goalEnabled: true,
    periodCalculationEnabled: true,
    carryOverEnabled: false,
    carryOverAmount: '0',
    manualCarryOverEnabled: false,
    manualCarryOverAmount: '0',
  },
  savingGoalSettings: {
    goalAmount: '100000',
    goalPeriod: '30',
    currentSaving: '0',
  },
  savingGoals: [],
  budgetsByMonth: {
    '2026-05': makeMonthlyBudgetSnapshot({
      monthlyIncome: 450000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '100000',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '100000',
        goalPeriod: '30',
        currentSaving: '0',
      },
      createdAt: '2026-05-01T00:00:00.000Z',
    }),
    '2026-06': makeMonthlyBudgetSnapshot({
      monthlyIncome: 450000,
      budgetSettings: {
        useManualBudget: false,
        manualDailyBudget: '',
        manualDailyBudgetEnabled: false,
        fixedExpenseAmount: '100000',
        autoIncludeRecurringExpenses: true,
        emergencyFundAmount: '50000',
        goalEnabled: true,
        periodCalculationEnabled: true,
        carryOverEnabled: false,
        carryOverAmount: '0',
        manualCarryOverEnabled: false,
        manualCarryOverAmount: '0',
      },
      savingGoalSettings: {
        goalAmount: '100000',
        goalPeriod: '30',
        currentSaving: '0',
      },
    }),
  },
  recurringExpenses: [
    makeRecurringExpense({
      id: 'overbudget-recurring-01',
      name: '기숙사비',
      amount: 150000,
      paymentDay: 1,
      category: RECURRING_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeRecurringExpense({
      id: 'overbudget-recurring-02',
      name: '휴대폰 요금',
      amount: 50000,
      paymentDay: 10,
      category: RECURRING_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
  ],
  expenseRecords: [
    makeExpenseRecord({
      id: 'overbudget-expense-01',
      date: '2026-04-25T09:00:00',
      amount: 40000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-02',
      date: '2026-05-01T08:30:00',
      amount: 80000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-03',
      date: '2026-05-02T13:00:00',
      amount: 60000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-04',
      date: '2026-05-03T18:30:00',
      amount: 70000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-05',
      date: '2026-05-09T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-06',
      date: '2026-05-10T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-07',
      date: '2026-05-11T09:00:00',
      amount: 20000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-08',
      date: '2026-06-01T08:30:00',
      amount: 35000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-09',
      date: '2026-06-05T13:00:00',
      amount: 30000,
      category: GENERAL_EXPENSE_CATEGORIES[1],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-10',
      date: '2026-06-10T18:30:00',
      amount: 25000,
      category: GENERAL_EXPENSE_CATEGORIES[5],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-11',
      date: '2026-06-15T20:40:00',
      amount: 45000,
      category: GENERAL_EXPENSE_CATEGORIES[2],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-12',
      date: '2026-06-24T09:00:00',
      amount: 50000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
    makeExpenseRecord({
      id: 'overbudget-expense-13',
      date: '2026-06-15T12:30:00',
      amount: 60000,
      category: GENERAL_EXPENSE_CATEGORIES[0],
      paymentMethod: '카드',
    }),
  ],
};
export const LEGACY_SEED_EMAILS = [
  'empty@pingo.com',
  'carryover@pingo.com',
  'manual-carryover@pingo.com',
  'recurring-before@pingo.com',
  'recurring-after@pingo.com',
];

export const SEED_ACCOUNTS = [firstAccount, secondAccount, dangerAccount, overbudgetAccount];

export function buildSeedUsers() {
  return SEED_ACCOUNTS.map(({ name, email, password }) => ({
    name,
    email,
    password,
  }));
}

export function buildSeedAccountData() {
  return SEED_ACCOUNTS.reduce((accumulator, account) => {
    accumulator[account.email] = {
      monthlyIncome: account.monthlyIncome,
      budgetSettings: account.budgetSettings,
      budgetsByMonth: account.budgetsByMonth || {},
      savingGoalSettings: account.savingGoalSettings,
      savingGoals: account.savingGoals || [],
      expenseRecords: account.expenseRecords || [],
      recurringExpenses: account.recurringExpenses || [],
      carryOverState: account.carryOverState || {
        lastCalculatedMonth: '',
        monthlySnapshots: {},
      },
    };

    return accumulator;
  }, {});
}

export function getPrimarySeedAccount() {
  return firstAccount;
}
